USE [master]
GO

/****** Object:  Database [yasin]    Script Date: 9.06.2024 17:31:36 ******/
CREATE DATABASE [yasin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'yasin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\yasin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'yasin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\yasin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [yasin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [yasin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [yasin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [yasin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [yasin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [yasin] SET ARITHABORT OFF 
GO

ALTER DATABASE [yasin] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [yasin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [yasin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [yasin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [yasin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [yasin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [yasin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [yasin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [yasin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [yasin] SET  ENABLE_BROKER 
GO

ALTER DATABASE [yasin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [yasin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [yasin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [yasin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [yasin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [yasin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [yasin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [yasin] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [yasin] SET  MULTI_USER 
GO

ALTER DATABASE [yasin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [yasin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [yasin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [yasin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [yasin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [yasin] SET QUERY_STORE = OFF
GO

ALTER DATABASE [yasin] SET  READ_WRITE 
GO


